//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.28 at 02:59:59 PM CST 
//


package mx.gob.sat.comercioexterior11;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.comercioexterior11 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.comercioexterior11
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComercioExterior }
     * 
     */
    public ComercioExterior createComercioExterior() {
        return new ComercioExterior();
    }

    /**
     * Create an instance of {@link ComercioExterior.Mercancias }
     * 
     */
    public ComercioExterior.Mercancias createComercioExteriorMercancias() {
        return new ComercioExterior.Mercancias();
    }

    /**
     * Create an instance of {@link ComercioExterior.Mercancias.Mercancia }
     * 
     */
    public ComercioExterior.Mercancias.Mercancia createComercioExteriorMercanciasMercancia() {
        return new ComercioExterior.Mercancias.Mercancia();
    }

    /**
     * Create an instance of {@link ComercioExterior.Destinatario }
     * 
     */
    public ComercioExterior.Destinatario createComercioExteriorDestinatario() {
        return new ComercioExterior.Destinatario();
    }

    /**
     * Create an instance of {@link ComercioExterior.Receptor }
     * 
     */
    public ComercioExterior.Receptor createComercioExteriorReceptor() {
        return new ComercioExterior.Receptor();
    }

    /**
     * Create an instance of {@link ComercioExterior.Emisor }
     * 
     */
    public ComercioExterior.Emisor createComercioExteriorEmisor() {
        return new ComercioExterior.Emisor();
    }

    /**
     * Create an instance of {@link ComercioExterior.Propietario }
     * 
     */
    public ComercioExterior.Propietario createComercioExteriorPropietario() {
        return new ComercioExterior.Propietario();
    }

    /**
     * Create an instance of {@link ComercioExterior.Mercancias.Mercancia.DescripcionesEspecificas }
     * 
     */
    public ComercioExterior.Mercancias.Mercancia.DescripcionesEspecificas createComercioExteriorMercanciasMercanciaDescripcionesEspecificas() {
        return new ComercioExterior.Mercancias.Mercancia.DescripcionesEspecificas();
    }

    /**
     * Create an instance of {@link ComercioExterior.Destinatario.Domicilio }
     * 
     */
    public ComercioExterior.Destinatario.Domicilio createComercioExteriorDestinatarioDomicilio() {
        return new ComercioExterior.Destinatario.Domicilio();
    }

    /**
     * Create an instance of {@link ComercioExterior.Receptor.Domicilio }
     * 
     */
    public ComercioExterior.Receptor.Domicilio createComercioExteriorReceptorDomicilio() {
        return new ComercioExterior.Receptor.Domicilio();
    }

    /**
     * Create an instance of {@link ComercioExterior.Emisor.Domicilio }
     * 
     */
    public ComercioExterior.Emisor.Domicilio createComercioExteriorEmisorDomicilio() {
        return new ComercioExterior.Emisor.Domicilio();
    }

}
