//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 12:24:31 PM CST 
//


package mx.com.fact.schema.pepsico;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.com.fact.schema.pepsico package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.com.fact.schema.pepsico
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestCFD }
     * 
     */
    public RequestCFD createRequestCFD() {
        return new RequestCFD();
    }

    /**
     * Create an instance of {@link RequestCFD.Recepciones }
     * 
     */
    public RequestCFD.Recepciones createRequestCFDRecepciones() {
        return new RequestCFD.Recepciones();
    }

    /**
     * Create an instance of {@link RequestCFD.Recepciones.Recepcion }
     * 
     */
    public RequestCFD.Recepciones.Recepcion createRequestCFDRecepcionesRecepcion() {
        return new RequestCFD.Recepciones.Recepcion();
    }

    /**
     * Create an instance of {@link RequestCFD.Documento }
     * 
     */
    public RequestCFD.Documento createRequestCFDDocumento() {
        return new RequestCFD.Documento();
    }

    /**
     * Create an instance of {@link RequestCFD.Proveedor }
     * 
     */
    public RequestCFD.Proveedor createRequestCFDProveedor() {
        return new RequestCFD.Proveedor();
    }

    /**
     * Create an instance of {@link RequestCFD.Recepciones.Recepcion.Concepto }
     * 
     */
    public RequestCFD.Recepciones.Recepcion.Concepto createRequestCFDRecepcionesRecepcionConcepto() {
        return new RequestCFD.Recepciones.Recepcion.Concepto();
    }

}
